### ISSUE TITLE
Сделать миграцию для бд стенда

### ISSUE THREAD

**Issue by IgorShaposhnikov** [The-Elegance/IotRemoteLaboratory#21]

**Comment by IuxMorti** [comment]
https://github.com/The-Elegance/IotRemoteLaboratory/pull/17/commits/2d72b791c2cb950aff87c0bd09167152c1016993

**Comment by IuxMorti** [comment]
https://github.com/The-Elegance/IotRemoteLaboratory/pull/17/commits/2d72b791c2cb950aff87c0bd09167152c1016993
